import { useState, useEffect, useRef, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import { ArrowLeft, ArrowRight, Check, Cloud, X, FileText, Eye, Trash2, Upload, Sparkles, CheckCircle2, Save, AlertTriangle, CalendarDays, Headphones, AlertCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { SubmissionProgressBar } from '@/components/modals/SubmissionProgressBar';
import { SubmissionSuccessDialog } from '@/components/modals/SubmissionSuccessDialog';
import { ibmbAPI } from '@/api/ibmb';
import { listTranscriptionAudio } from '@/api/transcription';
import { parseActivityLogWithGemini, matchesToFormState } from '@/utils/parseActivityLog';
import { TranscriptionPanel } from '@/components/panels/TranscriptionPanel';

// ─── Icons (matching InvestigationModal) ──────────────────────────────────────
const ComplaintIcon = ({ active }) => (
  <svg width="22" height="22" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="7" r="4" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" fill="none"/><path d="M4 21V19C4 16.79 5.79 15 8 15H16C18.21 15 20 16.79 20 19V21" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round"/></svg>
);
const InvestigationIcon = ({ active }) => (
  <svg width="22" height="22" viewBox="0 0 21 21" fill="none"><path d="M13 2H5C3.9 2 3 2.9 3 4V18C3 19.1 3.9 20 5 20H15C16.1 20 17 19.1 17 18V6L13 2Z" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><circle cx="10" cy="12" r="2" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5"/><path d="M11.5 13.5L13 15" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round"/></svg>
);
const ActionTakenIcon = ({ active }) => (
  <svg width="22" height="22" viewBox="0 0 24 21" fill="none"><circle cx="10" cy="10.5" r="8" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5"/><path d="M6 10.5L9 13.5L14 8.5" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
);
const SystemFactsIcon = ({ active }) => (
  <svg width="22" height="22" viewBox="0 0 28 21" fill="none"><path d="M1 10.5C1 10.5 5 2.5 14 2.5C23 2.5 27 10.5 27 10.5C27 10.5 23 18.5 14 18.5C5 18.5 1 10.5 1 10.5Z" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><circle cx="14" cy="10.5" r="4" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5"/></svg>
);
const ConclusionIcon = ({ active }) => (
  <svg width="22" height="22" viewBox="0 0 21 21" fill="none"><path d="M16 2H5C3.9 2 3 2.9 3 4V17C3 18.1 3.9 19 5 19H16C17.1 19 18 18.1 18 17V4C18 2.9 17.1 2 16 2Z" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5"/><path d="M7 10L9.5 12.5L14 8" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M7 15H14" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round"/></svg>
);
const AnnxIcon = ({ active }) => (
  <svg width="22" height="22" viewBox="0 0 21 21" fill="none"><path d="M18.5 9.5V15.5C18.5 16.6 17.4 17.5 16.5 17.5H4.5C3.4 17.5 2.5 16.6 2.5 15.5V5.5C2.5 4.4 3.4 3.5 4.5 3.5H10.5" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M14.5 2.5L18.5 6.5" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round"/><path d="M14.5 2.5V6.5H18.5" stroke={active?"#fff":"#AFAFAF"} strokeWidth="1.5" strokeLinecap="round"/></svg>
);

const steps = [
  { id: 1, title: 'Customer / Complaint Details', Icon: ComplaintIcon },
  { id: 2, title: 'Investigation', Icon: InvestigationIcon },
  { id: 3, title: 'Action Taken', Icon: ActionTakenIcon },
  { id: 4, title: 'System Facts / Observations', Icon: SystemFactsIcon },
  { id: 5, title: 'Conclusion', Icon: ConclusionIcon },
  { id: 6, title: 'Annx', Icon: AnnxIcon },
];

const txnPatternOptions = [
  'Transaction pattern seems Normal as compared with previous history',
  'Transaction pattern seems suspicious as compared with pervious history',
  'No previous history observed, current activity shows frequent use / explorer of multiple options',
];

// ─── Validation: Required fields per step ────────────────────────────────────
const REQUIRED_FIELDS = {
  1: [
    { key: 'disputeAmountAtRisk', label: 'Dispute Amount At Risk' },
    { key: 'fmsAlertGenerated', label: 'Alert Generated by FMS', hasDefault: true, defaultVal: 'no' },
  ],
  2: [
    // Customer Contact
    { key: 'cxCallDatetime', label: 'Customer Call at Contact Centre' },
    { key: 'initialCustomerStance', label: 'Customer Stance as per Initial Call' },
    { key: 'ioCallMade', label: 'Call was made to the Customer' },
    { key: 'contactEstablished', label: 'Contact Established' },
    { key: 'customerCli', label: 'Customer CLI Number' },
    { key: 'rcChannel', label: 'Calling RC (Recording Channel)' },
    { key: 'ioCallDatetime', label: 'Customer Communication Date / Time (IO Call)' },
    { key: 'letterSent', label: 'Communication Letter Sent' },
    { key: 'ioCallStance', label: 'Customer Stance as per IO Call' },
    { key: 'simBlocked', label: 'Customer / Beneficiary SIM Blocked' },
    // Channel & Device Analysis
    { key: 'mbCreationDatetime', label: 'IB/MB Channel Creation' },
    { key: 'dcCreationDatetime', label: 'Debit Card Creation' },
    { key: 'ccCreationDatetime', label: 'Credit Card Creation' },
    { key: 'mbCreationSource', label: 'Source of IB/MB Channel Creation' },
    { key: 'hblMobileAppActivityReview', label: 'HBL Mobile App Activity Review' },
    { key: 'userSinceDatetime', label: 'User Since' },
    { key: 'initialDeviceId', label: 'Initial Device' },
    { key: 'loginId', label: 'Customer Login ID' },
    { key: 'loginIp', label: 'User IP Address / LAT / LOG' },
    { key: 'credentialChange', label: 'Change of Login ID & Password', hasDefault: true, defaultVal: 'no' },
    { key: 'tpinChange', label: 'Change of TPin', hasDefault: true, defaultVal: 'no' },
    { key: 'newDevice', label: 'New Device Registration', hasDefault: true, defaultVal: 'no' },
    // Limits & Behavioral Analysis
    { key: 'limitEnhanced', label: 'Limit Enhancement', hasDefault: true, defaultVal: 'no' },
    { key: 'previousLimit', label: 'Customer Default / Previous Limit' },
    { key: 'newLimit', label: 'Customer New Limit' },
    { key: 'limitMode', label: 'Mode of Limit Enhancement' },
    { key: 'txnPattern', label: 'Customer Disputed Transaction Pattern' },
    { key: 'deviceChange', label: 'Change in Device Detail', hasDefault: true, defaultVal: 'no' },
    { key: 'ipChange', label: 'Change of IP / Location', hasDefault: true, defaultVal: 'no' },
    { key: 'productsAvailed', label: 'Consumer Product Availed' },
    { key: 'otpDelivered', label: 'SMS / OTP Sent to the Customer' },
  ],
  3: [
    { key: 'deviceBlockedFlag', label: 'Blocking of Observed Device' },
    { key: 'fraudsterNumberReported', label: 'Fraudster / Perpetrator Mobile Number' },
    { key: 'fundLayeredFlag', label: 'Fund Layered A/C' },
    { key: 'pstrFlag', label: 'PSTR' },
    { key: 'piiReviewedFlag', label: 'P-II Reviewed' },
    { key: 'frmuReviewFlag', label: 'FRMU review on Staff Feedback' },
    { key: 'customerAccountOpeningDate', label: 'Customer Account Opening Date' },
    { key: 'customerAccountType', label: 'Customer Account Type' },
    { key: 'kycReviewDebitCreditCount', label: 'KYC Review - Debit / Credit Count' },
    { key: 'customerProfileKyc', label: 'Customer Profile as per system / KYC' },
  ],
  4: [
    { key: 'gapIdentified', label: 'Any Gap Identified' },
    { key: 'factFindings', label: 'Fact Findings' },
    { key: 'controlBreaches', label: 'Control Breaches' },
    { key: 'rootCause', label: 'Root Cause' },
    { key: 'fraudTypeSystem', label: 'Type of Fraud Identified by the System' },
  ],
  5: [
    { key: 'netLossBooked', label: 'Net Loss Booked' },
    { key: 'finalConclusionType', label: 'Conclusion' },
    { key: 'recommendation', label: 'Recommendation' },
    { key: 'actionOwner', label: 'Action Owner' },
    { key: 'actionStatus', label: 'Status of Action Recommended' },
  ],
  // Step 6 (Annx) has no required fields
};

/** Returns array of { key, label } for missing required fields in a step */
const getStepErrors = (stepNum, formData) => {
  const fields = REQUIRED_FIELDS[stepNum] || [];
  return fields.filter(({ key, hasDefault, defaultVal }) => {
    const val = formData[key];
    // Fields with explicit defaults (yes/no chips) are considered filled if they have any value
    // But if the value is still the initial default AND hasDefault is true, we still count it as filled
    // because the user sees a pre-selected chip
    if (hasDefault) return false; // pre-selected defaults count as filled
    return val === '' || val === null || val === undefined;
  });
};

/** Returns count of missing required fields in a step */
const getStepErrorCount = (stepNum, formData) => getStepErrors(stepNum, formData).length;

/** Returns set of errored field keys for a step */
const getStepErrorKeys = (stepNum, formData) => new Set(getStepErrors(stepNum, formData).map(e => e.key));

// ─── Helpers ──────────────────────────────────────────────────────────────────
const formatCurrency = (amount) => new Intl.NumberFormat('en-PK', { style: 'currency', currency: 'PKR', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);
const formatDateText = (value) => {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return format(date, 'dd-MMM-yyyy');
};
const formatDateTimeText = (value) => {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return format(date, 'dd-MMM-yyyy hh:mm a');
};

const resolveMediaUrl = (pathOrUrl) => {
  if (!pathOrUrl) return '';
  if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) return pathOrUrl;

  const apiBase = (import.meta.env.VITE_API_URL || 'http://localhost:8000/api').replace(/\/+$/, '');
  const origin = apiBase.endsWith('/api') ? apiBase.slice(0, -4) : apiBase;

  return pathOrUrl.startsWith('/') ? `${origin}${pathOrUrl}` : `${origin}/${pathOrUrl}`;
};

const mapServerAudioToPanelFile = (audio) => ({
  id: audio.id,
  name: audio.file_name,
  size: `${Math.max(1, Math.round((audio.file_size || 0) / 1024))} KB`,
  type: audio.file_type || 'cx_call',
  url: resolveMediaUrl(audio.file),
  rawFile: null,
  backendId: audio.id,
  backendStatus: audio.status,
  transcriptionText: audio.transcription?.text || null,
  uploadedAt: audio.created_at,
  serverFile: true,
});

const ACTIVITY_LOG_FEEDBACK_DURATION_MS = 7000;

// ─── Reusable Sub-components ─────────────────────────────────────────────────
function StepIndicator({ currentStep, onStepClick, stepErrorCounts, validationTriggered }) {
  return (
    <div className="flex items-center justify-between px-6 py-4 bg-white border-b border-[#E5E7EB] overflow-x-auto">
      {steps.map((step, index) => {
        const isActive = currentStep === step.id;
        const errorCount = validationTriggered ? (stepErrorCounts[step.id] || 0) : 0;
        const hasErrors = errorCount > 0;
        const isComplete = validationTriggered && !hasErrors && step.id <= 5; // Step 6 (Annx) always OK
        const isCompleted = !validationTriggered && currentStep > step.id; // original green-check behavior
        return (
          <div key={step.id} className="flex items-center flex-1 last:flex-none">
            <button
              type="button"
              onClick={() => onStepClick(step.id)}
              className="flex items-center gap-2.5 min-w-max cursor-pointer group"
            >
              <div className="relative">
                <div className={cn(
                  "w-10 h-10 rounded-full flex items-center justify-center transition-all duration-300 shrink-0",
                  isComplete ? "bg-[#22C55E] group-hover:bg-[#16A34A]" :
                  isCompleted ? "bg-[#22C55E] group-hover:bg-[#16A34A]" :
                  isActive ? "bg-[#2064B7] shadow-lg shadow-[#2064B7]/30" :
                  hasErrors ? "bg-[#FEF2F2] border-2 border-[#EF4444] group-hover:bg-[#FEE2E2]" :
                  "bg-[#F3F4F6] border border-[#D1D5DB] group-hover:border-[#2064B7] group-hover:bg-[#EFF6FF]"
                )}>
                  {isComplete ? <Check className="w-5 h-5 text-white" /> :
                   isCompleted ? <Check className="w-5 h-5 text-white" /> :
                   hasErrors ? <AlertCircle className="w-5 h-5 text-[#EF4444]" /> :
                   <step.Icon active={isActive} />}
                </div>
                {hasErrors && (
                  <span className="absolute -top-1.5 -right-1.5 min-w-[18px] h-[18px] rounded-full bg-[#EF4444] text-white text-[10px] font-bold flex items-center justify-center px-1 shadow-sm">
                    {errorCount}
                  </span>
                )}
              </div>
              <span className={cn(
                "text-[13px] font-medium whitespace-nowrap hidden lg:inline transition-colors",
                isActive ? "text-[#2064B7] font-semibold" :
                isComplete || isCompleted ? "text-[#22C55E] group-hover:text-[#16A34A]" :
                hasErrors ? "text-[#EF4444] font-semibold" :
                "text-[#9CA3AF] group-hover:text-[#2064B7]"
              )}>{step.title}</span>
            </button>
            {index < steps.length - 1 && (
              <div className={cn("h-[2px] flex-1 mx-3 min-w-[20px] rounded-full transition-colors",
                isComplete || isCompleted ? "bg-[#22C55E]" : "bg-[#E5E7EB]"
              )} />
            )}
          </div>
        );
      })}
    </div>
  );
}

const ChipOption = ({ value, selected, onChange, label }) => (
  <button
    type="button"
    onClick={() => onChange(value)}
    className={cn(
      'inline-flex items-center gap-2 py-1 text-[13px] font-medium transition-colors',
      selected ? 'text-[#111827]' : 'text-[#6B7280] hover:text-[#2064B7]'
    )}
  >
    <span
      className={cn(
        'w-5 h-5 rounded-full border-2 flex items-center justify-center transition-colors',
        selected ? 'border-[#2064B7]' : 'border-[#D1D5DB]'
      )}
    >
      <span className={cn('w-2.5 h-2.5 rounded-full transition-colors', selected ? 'bg-[#2064B7]' : 'bg-transparent')} />
    </span>
    <span>{label}</span>
  </button>
);

const FormField = ({ label, required, children, output, large, isInput, error, highlighted = false }) => (
  <div className={cn(
    "grid w-full grid-cols-[1fr_1.2fr_1.2fr] gap-0 border-b border-[#E5E7EB] last:border-b-0 transition-colors",
    highlighted && "bg-[#F0FDF4] border-[#BBF7D0]",
    large ? "min-h-[80px]" : "min-h-[44px]"
  )}>
    <div className={cn(
      "min-w-0 flex flex-col justify-center px-4 py-2.5 border-r border-[#E5E7EB] transition-colors",
      highlighted ? "bg-[#F0FDF4]" : "bg-[#F9FAFB]"
    )}>
      <span className="text-[13px] font-semibold text-[#374151] leading-[18px] break-words">
        {label}{required && <span className="text-[#EF4444] ml-0.5">*</span>}
      </span>
      {error && (
        <span className="flex items-center gap-1 mt-1">
          <AlertCircle className="w-3 h-3 text-[#EF4444] shrink-0" />
          <span className="text-[11px] text-[#EF4444] font-medium">Required</span>
        </span>
      )}
    </div>
    <div className={cn(
      "min-w-0 flex border-r border-[#E5E7EB] transition-colors",
      highlighted ? "bg-[#F0FDF4]" : "bg-white",
      isInput ? "items-stretch p-0" : "items-center px-4 py-2.5"
    )}>{children}</div>
    <div className={cn(
      "min-w-0 flex items-center px-4 py-2.5 transition-colors",
      highlighted ? "bg-[#F0FDF4]" : "bg-[#F0F7FF]"
    )}>
      <span className="w-full text-[12px] text-[#6B7280] leading-[17px] whitespace-pre-wrap break-words">{output || '—'}</span>
    </div>
  </div>
);

const SectionDivider = ({ title }) => (
  <div className="bg-[#EFF6FF] px-4 py-2 border-b border-[#E5E7EB]">
    <span className="text-[11px] font-bold text-[#2064B7] uppercase tracking-wider">{title}</span>
  </div>
);

const DateInputWithIcon = ({ type = 'date', value, onChange, placeholder }) => {
  const inputRef = useRef(null);
  const openPicker = () => {
    const input = inputRef.current;
    if (!input) return;
    input.showPicker?.();
    input.focus();
  };

  return (
    <div className="relative w-full h-full">
      <button
        type="button"
        onClick={openPicker}
        className="absolute left-3 top-1/2 -translate-y-1/2 text-[#2064B7] z-10"
      >
        <CalendarDays className="w-4 h-4" />
      </button>
      <Input
        ref={inputRef}
        type={type}
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        className="no-native-picker w-full h-full border-0 bg-transparent focus-visible:ring-0 pl-10 pr-4 py-2.5 rounded-none text-[13px] [&::-webkit-calendar-picker-indicator]:opacity-0 [&::-webkit-calendar-picker-indicator]:pointer-events-none"
        style={{ WebkitAppearance: 'none', appearance: 'none' }}
      />
    </div>
  );
};

const AutoGrowTextarea = ({ className, value, onChange, ...props }) => {
  const textareaRef = useRef(null);

  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }, [value]);

  return (
    <textarea
      ref={textareaRef}
      value={value}
      onChange={onChange}
      className={cn(
        'w-full min-h-[80px] border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px] leading-[1.5] overflow-x-hidden whitespace-pre-wrap break-words resize-y outline-none',
        className
      )}
      style={{ fieldSizing: 'fixed' }}
      {...props}
    />
  );
};

// ─── Main Component ──────────────────────────────────────────────────────────
export function InvestigationFormPage({ currentRole = 'investigator', currentUser = null }) {
  const { id } = useParams();
  const navigate = useNavigate();
  const [currentStep, setCurrentStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submissionStep, setSubmissionStep] = useState(0);
  const [showSuccess, setShowSuccess] = useState(false);
  const [isDirty, setIsDirty] = useState(false);      // true when form has unsaved changes
  const [isSaving, setIsSaving] = useState(false);    // true while save animation plays
  const [showExitPrompt, setShowExitPrompt] = useState(false); // unsaved-changes warning
  const [pendingNavDest, setPendingNavDest] = useState(null);  // where we want to go after confirm
  const fileInputRef = useRef(null);
  const [uploadedFiles, setUploadedFiles] = useState([]);
  const [isDragOver, setIsDragOver] = useState(false);
  const activityLogRef = useRef(null);
  const [logParseResult, setLogParseResult] = useState(null); // { matches, unmatchedLines }
  const [showLogBanner, setShowLogBanner] = useState(false);
  const [autoFilledFieldKeys, setAutoFilledFieldKeys] = useState(new Set());
  const activityLogFeedbackTimerRef = useRef(null);
  const [transcriptionOpen, setTranscriptionOpen] = useState(false);
  const [transcriptionFiles, setTranscriptionFiles] = useState([]);
  const [investigationId, setInvestigationId] = useState(null);
  const hydratedFromDraftRef = useRef(false);
  const [validationTriggered, setValidationTriggered] = useState(false); // true after first Review Report attempt

  const [loading, setLoading] = useState(true);
  const [caseData, setCaseData] = useState(null);
  const [loadError, setLoadError] = useState(null);
  const [rejectionReason, setRejectionReason] = useState('');

  const isSupervisorOrAdmin = currentRole === 'supervisor' || currentRole === 'admin';
  const isAssignedInvestigator =
    currentRole === 'investigator' &&
    String(currentUser?.name || '').trim().toLowerCase() ===
      String(caseData?.assigned_to?.name || caseData?.assigned_to_name || '').trim().toLowerCase();
  const canAccessInvestigation = isSupervisorOrAdmin || isAssignedInvestigator;

  const [f, setF] = useState({
    // Step 1: Customer / Complaint Details
    investigationOfficer: '', complaintNo: '', caseReferenceNo: '', caseReceivingChannel: '',
    disputeChannel: '', fraudTypeField: '',
    disputeAmountAtRisk: '', expectedRecovery: 'NIL', expectedRecoveryMemberBank: 'NIL', disputedTxnDetails: '', fmsAlertGenerated: 'no',
    incidentDate: '', incidentDateTo: '', caseReceivingDate: '',
    customerNameField: '', customerAccountNoField: '', branchCodeField: '',
    // Step 2: Investigation — Customer Contact
    cxCallDatetime: '', initialCustomerStance: '', ioCallMade: '', contactEstablished: '',
    customerCli: '', rcChannel: '', ioCallDatetime: '', letterSent: '',
    ioCallStance: '', simBlocked: '',
    // Step 2: Channel & Device Analysis
    mbCreationDatetime: '', dcCreationDatetime: '', ccCreationDatetime: '', mbCreationSource: '',
    hblMobileAppActivityReview: '', userSinceDatetime: '',
    initialDeviceId: '', loginId: '', loginIp: '', credentialChange: 'no',
    tpinChange: 'no', newDevice: 'no',
    // Step 2: Limits & Behavioral Analysis
    limitEnhanced: 'no', previousLimit: '', newLimit: '', limitMode: '',
    txnPattern: '', deviceChange: 'no', ipChange: 'no', productsAvailed: '', otpDelivered: '',
    // Step 3: Action Taken
    deviceBlockedFlag: '', fraudsterNumberReported: '', ftdhStatus: '', fundLayeredFlag: '',
    pstrFlag: '', piiReviewedFlag: '', suspectedStaffName: 'NA', suspectedStaffFeedback: 'NA',
    frmuReviewFlag: '', customerAccountOpeningDate: '', customerAccountType: '',
    kycReviewDebitCreditCount: '', customerProfileKyc: '', frmAlert: '',
    // Step 4: System Facts
    gapIdentified: '', factFindings: '', controlBreaches: '', controlBreachesObserved: '',
    rootCause: '', fraudTypeSystem: '',
    // Step 5: Conclusion
    netLossBooked: '', finalConclusionType: '', recommendation: '', actionOwner: '', actionStatus: '',
  });

  // ─── Computed validation data ────────────────────────────────────────
  const stepErrorCounts = useMemo(() => {
    if (!validationTriggered) return {};
    const counts = {};
    for (let s = 1; s <= 5; s++) counts[s] = getStepErrorCount(s, f);
    return counts;
  }, [validationTriggered, f]);

  const currentStepErrorKeys = useMemo(() => {
    if (!validationTriggered) return new Set();
    return getStepErrorKeys(currentStep, f);
  }, [validationTriggered, currentStep, f]);

  const totalErrors = useMemo(() => {
    if (!validationTriggered) return 0;
    return Object.values(stepErrorCounts).reduce((sum, c) => sum + c, 0);
  }, [validationTriggered, stepErrorCounts]);

  // ─── Load case + investigation from API ──────────────────────────────
  useEffect(() => {
    let cancelled = false;
    async function loadData() {
      try {
        setLoading(true);
        setLoadError(null);

        // Load case data
        const caseRes = await ibmbAPI.getCase(id);
        if (cancelled) return;
        setCaseData(caseRes.data);

        // Load or create investigation (auto-pre-fills on first access)
        const invRes = await ibmbAPI.getInvestigation(id);
        if (cancelled) return;
        const inv = invRes.data;
        const hasRejectedDraft = inv.draftStatus === 'rejected';
        setRejectionReason(hasRejectedDraft ? (inv.rejectionReason || '') : '');

        const shouldShowReportPreview =
          currentRole === 'investigator' && (
            inv.draftStatus === 'submitted' ||
            inv.draftStatus === 'approved' ||
            caseRes.data?.status === 'pending_review' ||
            caseRes.data?.status === 'approved' ||
            caseRes.data?.status === 'closed'
          );

        if (shouldShowReportPreview) {
          navigate(`/cases/${id}/investigation-review`, { replace: true });
          return;
        }

        setInvestigationId(inv.id || null);

        // Hydrate form state from investigation data
        // Only pick form-relevant keys (skip metadata like id, case, files, etc.)
        const formKeys = Object.keys(f);
        const patch = {};
        for (const key of formKeys) {
          if (inv[key] !== undefined && inv[key] !== null && inv[key] !== '') {
            patch[key] = inv[key];
          }
        }
        setF(prev => ({ ...prev, ...patch }));
        setCurrentStep(inv.currentStep || 1);

        // Hydrate persisted transcriptions linked to this investigation
        if (inv.id) {
          try {
            const audios = await listTranscriptionAudio('ibmb_investigation', inv.id);
            if (!cancelled) {
              setTranscriptionFiles((audios || []).map(mapServerAudioToPanelFile));
            }
          } catch {
            if (!cancelled) setTranscriptionFiles([]);
          }
        }

        // Load investigation files
        try {
          const filesRes = await ibmbAPI.listInvestigationFiles(id);
          if (!cancelled) {
            setUploadedFiles(
              filesRes.data.map((file) => ({
                id: file.id,
                name: file.original_filename,
                size: `${Math.round(file.file_size / 1024)} KB`,
                totalSize: `${Math.round(file.file_size / 1024)} KB`,
                status: 'Completed',
                serverFile: true,
              }))
            );
          }
        } catch {
          // Files endpoint may 404 if investigation was just created — that's fine
        }
      } catch (err) {
        if (!cancelled) {
          console.error('Failed to load investigation data:', err);
          setLoadError(err.response?.data?.detail || 'Failed to load investigation data.');
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    loadData();
    return () => { cancelled = true; };
  }, [id, currentRole, navigate]);

  useEffect(() => {
    if (currentStep !== 2 && transcriptionOpen) {
      setTranscriptionOpen(false);
    }
  }, [currentStep, transcriptionOpen]);

  useEffect(() => () => {
    if (activityLogFeedbackTimerRef.current) {
      clearTimeout(activityLogFeedbackTimerRef.current);
    }
  }, []);

  const clearActivityLogFeedback = () => {
    if (activityLogFeedbackTimerRef.current) {
      clearTimeout(activityLogFeedbackTimerRef.current);
      activityLogFeedbackTimerRef.current = null;
    }
    setShowLogBanner(false);
    setAutoFilledFieldKeys(new Set());
  };

  const set = (key, val) => {
    setF(p => ({ ...p, [key]: val }));
    setIsDirty(true);
  };

  const out = (field, value) => {
    const map = {
      ioCallMade: value === 'yes' ? 'Customer was contacted by the investigation officer.' : value === 'no' ? 'Customer was not contacted.' : '—',
      contactEstablished: value === 'yes' ? 'Contact was successfully established with the customer.' : value === 'no' ? 'Contact could not be established.' : '—',
      letterSent: value === 'yes' ? 'Communication letter was sent to the customer.' : value === 'no' ? 'Communication letter was not sent.' : '—',
      simBlocked: value === 'yes' ? 'Customer/Beneficiary SIM has been blocked.' : value === 'no' ? 'Customer/Beneficiary SIM was not blocked.' : '—',
      deviceBlockedFlag: value === 'yes' ? 'The observed device was marked as blocked.' : value === 'no' ? 'Device was not blocked.' : '—',
      fraudsterNumberReported: value === 'yes' ? 'Fraudster number reported to PTA.' : value === 'no' ? 'Fraudster number was not reported.' : '—',
      fundLayeredFlag: value === 'yes' ? 'Fund layering details shared by member bank.' : value === 'no' ? 'No detail shared by member bank related to layering.' : '—',
      pstrFlag: value === 'yes' ? 'PSTR was raised against the observed On-Us customer account.' : value === 'no' ? 'PSTR was not raised.' : '—',
      piiReviewedFlag: value === 'yes' ? 'P-II review was conducted.' : value === 'no' ? 'No fraudulent element observed. P-II was not reviewed.' : '—',
      gapIdentified: value === 'yes' ? 'Internal gap has been identified in this case.' : value === 'no' ? 'No internal gap is observed in this case.' : '—',
      controlBreaches: value === 'yes' ? 'Control breach has been identified.' : value === 'no' ? 'No Control Breach is observed.' : '—',
      credentialChange: value === 'yes' ? 'Credential change detected within last 2 months.' : value === 'no' ? 'No credential change detected.' : '—',
      tpinChange: value === 'yes' ? 'T-PIN change detected.' : value === 'no' ? 'No T-PIN change detected.' : '—',
      newDevice: value === 'yes' ? 'New device registration detected.' : value === 'no' ? 'No new device registration.' : '—',
      limitEnhanced: value === 'yes' ? 'Transaction limit was enhanced.' : value === 'no' ? 'No limit enhancement.' : '—',
      deviceChange: value === 'yes' ? 'Change in device detail detected.' : value === 'no' ? 'No change in device detail.' : value === 'na' ? '-' : '—',
      productsAvailed: value === 'yes' ? 'Consumer product availed.' : value === 'no' ? 'No consumer product availed.' : '—',
      ipChange: value === 'yes' ? 'Change of IP / location detected.' : value === 'no' ? 'No change in IP / location.' : '—',
      frmAlert: value === 'yes' ? 'FRM system alert was generated.' : value === 'no' ? 'No FRM system alert was generated.' : '—',
      hblMobileAppActivityReview: value === 'yes' ? 'HBL Mobile Application channel activity reviewed.' : value === 'no' ? 'HBL Mobile Application channel activity not reviewed.' : '—',
    };
    return map[field] || '—';
  };

  const handleSaveDraft = async () => {
    setIsSaving(true);
    try {
      await ibmbAPI.saveInvestigation(id, { ...f, currentStep });
      setIsDirty(false);
      toast.success('Draft saved', {
        description: 'Your investigation report progress has been saved.',
        duration: 3000,
      });
    } catch (err) {
      console.error('Failed to save draft:', err);
      toast.error('Failed to save draft', {
        description: err.response?.data?.detail || 'Please try again.',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleNavigateBack = () => {
    if (isDirty) {
      setPendingNavDest(`/cases/${id}`);
      setShowExitPrompt(true);
    } else {
      navigate(`/cases/${id}`);
    }
  };

  const handleDiscardAndExit = () => {
    setShowExitPrompt(false);
    setIsDirty(false);
    navigate(pendingNavDest);
  };

  const handleSaveAndExit = async () => {
    setShowExitPrompt(false);
    try {
      await ibmbAPI.saveInvestigation(id, { ...f, currentStep });
      setIsDirty(false);
      toast.success('Draft saved', { description: 'Your progress has been saved.', duration: 2000 });
      setTimeout(() => navigate(pendingNavDest), 600);
    } catch (err) {
      toast.error('Failed to save draft');
      navigate(pendingNavDest);
    }
  };

  const handleSubmit = async () => {
    setIsSubmitting(true); setSubmissionStep(1);
    for (let i = 1; i <= 6; i++) { await new Promise(r => setTimeout(r, 500)); setSubmissionStep(i); }
    await new Promise(r => setTimeout(r, 500));
    setIsSubmitting(false); setShowSuccess(true);
  };
  const handleReviewReport = async () => {
    // ── Validate all steps before allowing review ──
    setValidationTriggered(true);
    let allErrors = 0;
    let firstErrorStep = null;
    for (let s = 1; s <= 5; s++) {
      const count = getStepErrorCount(s, f);
      if (count > 0) {
        allErrors += count;
        if (firstErrorStep === null) firstErrorStep = s;
      }
    }
    if (allErrors > 0) {
      const stepWord = firstErrorStep === currentStep ? 'this step' : `Step ${firstErrorStep} (${steps.find(s => s.id === firstErrorStep)?.title})`;
      toast.error('Required fields missing', {
        description: `${allErrors} required field${allErrors > 1 ? 's are' : ' is'} empty. Check ${stepWord} to start.`,
        duration: 5000,
      });
      if (firstErrorStep !== currentStep) setCurrentStep(firstErrorStep);
      return;
    }

    // Save the latest draft before navigating to review
    try {
      await ibmbAPI.saveInvestigation(id, { ...f, currentStep: 6 });
      setIsDirty(false);
    } catch (err) {
      console.error('Failed to save before review:', err);
      toast.error('Failed to save draft before review');
      return;
    }
    navigate(`/cases/${id}/investigation-review`);
  };
  const handleSuccessClose = () => { setShowSuccess(false); setSubmissionStep(0); navigate(`/cases/${id}`); };

  // File upload handlers
  const handleFiles = async (files) => {
    const fileArr = Array.from(files);
    for (const file of fileArr) {
      const tempId = Date.now() + Math.random();
      // Add a placeholder entry
      setUploadedFiles(prev => [...prev, {
        id: tempId,
        name: file.name,
        size: `${Math.round(file.size / 1024)} KB`,
        totalSize: `${Math.round(file.size / 1024)} KB`,
        status: 'Uploading...',
        serverFile: false,
      }]);

      try {
        const formData = new FormData();
        formData.append('file', file);
        const res = await ibmbAPI.uploadInvestigationFile(id, formData);
        // Replace placeholder with server response
        setUploadedFiles(prev => prev.map(f =>
          f.id === tempId
            ? {
                id: res.data.id,
                name: res.data.original_filename,
                size: `${Math.round(res.data.file_size / 1024)} KB`,
                totalSize: `${Math.round(res.data.file_size / 1024)} KB`,
                status: 'Completed',
                serverFile: true,
              }
            : f
        ));
      } catch (err) {
        console.error('File upload failed:', err);
        // Remove failed placeholder
        setUploadedFiles(prev => prev.filter(f => f.id !== tempId));
        toast.error(`Failed to upload ${file.name}`);
      }
    }
  };
  const handleDrop = (e) => { e.preventDefault(); setIsDragOver(false); handleFiles(e.dataTransfer.files); };
  const getFileExt = (name) => name.split('.').pop().toUpperCase();

  // ─── Activity Log Upload Handler (Gemini API) ────────────────────────────────
  const [isParsingActivityLog, setIsParsingActivityLog] = useState(false);

  const handleActivityLogUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Reset input so same file can be re-uploaded
    e.target.value = '';

    // Show loading state
    setIsParsingActivityLog(true);
    if (activityLogFeedbackTimerRef.current) {
      clearTimeout(activityLogFeedbackTimerRef.current);
      activityLogFeedbackTimerRef.current = null;
    }
    setShowLogBanner(false);
    setAutoFilledFieldKeys(new Set());
    toast.loading('Analyzing activity log with AI...', { id: 'activity-log-parse' });

    try {
      // Use Gemini API for intelligent extraction
      const result = await parseActivityLogWithGemini(file);

      // Dismiss loading toast
      toast.dismiss('activity-log-parse');

      if (result.error) {
        setLogParseResult(null);
        toast.error(`AI extraction failed: ${result.error}`);
      } else if (result.matches.length > 0) {
        // Apply parsed values to form state
        const newValues = matchesToFormState(result.matches);
        setF(prev => ({ ...prev, ...newValues }));
        setIsDirty(true);

        const highlightedKeys = new Set(result.matches.map(m => m.field));
        setAutoFilledFieldKeys(highlightedKeys);
        setLogParseResult(result);
        setShowLogBanner(true);

        // Show success with summary
        const summary = result.summary || {};
        const summaryText = summary.totalRows
          ? ` (${summary.totalRows} rows, ${summary.devices || 0} devices, ${summary.failedLogins || 0} failed logins)`
          : '';
        toast.success(`AI extracted ${result.matches.length} fields${summaryText}`);
      } else {
        toast.warning('No fields could be extracted from the activity log');
        setLogParseResult({ matches: [], source: 'gemini', summary: {} });
      }

      // Clear feedback after timeout
      if (activityLogFeedbackTimerRef.current) {
        clearTimeout(activityLogFeedbackTimerRef.current);
      }
      activityLogFeedbackTimerRef.current = setTimeout(() => {
        setShowLogBanner(false);
        setAutoFilledFieldKeys(new Set());
        activityLogFeedbackTimerRef.current = null;
      }, ACTIVITY_LOG_FEEDBACK_DURATION_MS);

    } catch (err) {
      console.error('Activity log parsing error:', err);
      toast.dismiss('activity-log-parse');
      setShowLogBanner(false);
      setAutoFilledFieldKeys(new Set());
      setLogParseResult(null);
      toast.error('Failed to parse activity log: ' + (err.message || 'Unknown error'));
    } finally {
      setIsParsingActivityLog(false);
    }
  };

  if (loading) return (
    <div className="flex flex-col items-center justify-center h-64">
      <div className="w-8 h-8 border-4 border-[#2064B7] border-t-transparent rounded-full animate-spin" />
      <p className="mt-4 text-sm text-muted-foreground">Loading investigation...</p>
    </div>
  );

  if (loadError || !caseData) return (
    <div className="flex flex-col items-center justify-center h-64">
      <h2 className="text-xl font-semibold">{loadError || 'Case not found'}</h2>
      <Button className="mt-4" onClick={() => navigate('/cases')}>Back to Cases</Button>
    </div>
  );

  if (!canAccessInvestigation) {
    return (
      <div className="flex flex-col items-center justify-center h-64">
        <h2 className="text-xl font-semibold">Access restricted</h2>
        <p className="text-sm text-muted-foreground mt-2 text-center max-w-xl">
          Only the assigned investigator ({caseData.assigned_to?.name || 'N/A'}) can start or continue this investigation.
        </p>
        <Button className="mt-4" onClick={() => navigate(`/cases/${id}`)}>Back to Case Details</Button>
      </div>
    );
  }

  const customerName = caseData.customer.name;
  const customerCnic = caseData.customer.cnic;
  const customerAccount = caseData.customer.accounts?.[0]?.account_number || '';

  return (
    <>
      <div className="h-screen flex flex-col bg-white">
        {/* Header */}
        <div className="bg-[#2064B7] px-6 py-4 flex items-center justify-between shadow-lg">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={handleNavigateBack} className="text-white hover:bg-white/10">
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div>
              <h1 className="text-[22px] font-bold text-white">Investigation Report</h1>
              <p className="text-[12px] text-white/70">{caseData.reference_number}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {isDirty && (
              <span className="text-[11px] font-medium text-amber-300 bg-amber-400/10 border border-amber-400/20 px-2.5 py-1 rounded-full flex items-center gap-1 mr-1">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-300 animate-pulse" />
                Unsaved changes
              </span>
            )}
            <Button
              variant="outline"
              className="bg-white/10 text-white border-white/20 hover:bg-white/20 hover:text-white gap-2 transition-all"
              onClick={handleSaveDraft}
              disabled={isSaving}
            >
              <Save className={`w-4 h-4 ${isSaving ? 'animate-pulse' : ''}`} />
              {isSaving ? 'Saving...' : 'Save Draft'}
            </Button>
            {currentStep === 2 && (
              <Button
                variant="outline"
                className="bg-white/10 text-white border-white/20 hover:bg-white/20 hover:text-white gap-2 transition-all"
                onClick={() => activityLogRef.current?.click()}
                disabled={isParsingActivityLog}
              >
                {isParsingActivityLog ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    AI Extract from Log
                  </>
                )}
              </Button>
            )}
          </div>
        </div>

        {/* Activity Log Upload — hidden input */}
        <input
          ref={activityLogRef}
          type="file"
          accept=".txt,.csv,.log"
          onChange={handleActivityLogUpload}
          className="hidden"
        />

        {rejectionReason && (
          <div className="bg-[#FEF2F2] border-b border-[#FCA5A5] px-6 py-3 overflow-x-hidden">
            <div className="flex items-start gap-2.5 min-w-0">
              <AlertTriangle className="w-4 h-4 text-[#B91C1C] mt-0.5 shrink-0" />
              <div className="min-w-0">
                <p className="text-[13px] font-semibold text-[#991B1B]">Report rejected by supervisor</p>
                <p className="text-[13px] text-[#7F1D1D] whitespace-pre-wrap break-all [overflow-wrap:anywhere] max-w-full">
                  <span className="font-semibold">Comments:</span> {rejectionReason}
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Activity Log Parse Results Banner */}
        {currentStep === 2 && showLogBanner && logParseResult && (
          <div className="bg-[#F0FDF4] border-b border-[#BBF7D0] px-6 py-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-[#22C55E] flex items-center justify-center">
                  <Sparkles className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="text-[13px] font-semibold text-[#166534]">
                    {logParseResult.source === 'gemini' ? 'AI extraction completed' : 'Activity log extracted'} — {logParseResult.matches.length} field{logParseResult.matches.length !== 1 ? 's' : ''} auto-populated.
                  </p>
                  <p className="text-[12px] text-[#15803D] mt-1">
                    {logParseResult.source === 'gemini' && logParseResult.summary?.totalRows && (
                      <span className="mr-2">
                        Analyzed {logParseResult.summary.totalRows} rows • {logParseResult.summary.devices || 0} device(s) • {logParseResult.summary.failedLogins || 0} failed login(s)
                      </span>
                    )}
                    Highlighted rows indicate updated fields.
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                {logParseResult.source === 'gemini' && (
                  <span className="text-[10px] font-medium text-[#15803D] bg-[#DCFCE7] px-2 py-0.5 rounded-full">
                    Gemini 1.5 Flash
                  </span>
                )}
                <button onClick={clearActivityLogFeedback} className="text-[#166534] hover:text-[#14532D]">
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Unsaved Changes Exit Prompt */}
        {showExitPrompt && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-[200]">
            <div className="bg-white rounded-2xl shadow-2xl w-[420px] p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center">
                  <AlertTriangle className="w-5 h-5 text-amber-500" />
                </div>
                <div>
                  <h3 className="text-[16px] font-bold text-[#111827]">Unsaved Changes</h3>
                  <p className="text-[13px] text-[#6B7280]">Your investigation report has unsaved changes.</p>
                </div>
              </div>
              <p className="text-[13px] text-[#374151] mb-6 leading-relaxed">
                If you leave now, your current progress will be lost. Would you like to save your draft before exiting?
              </p>
              <div className="flex gap-3 justify-end">
                <Button
                  variant="outline"
                  className="text-[#EF4444] border-[#FCA5A5] hover:bg-red-50"
                  onClick={handleDiscardAndExit}
                >
                  Discard & Exit
                </Button>
                <Button
                  className="bg-[#2064B7] hover:bg-[#1a5298] text-white gap-2"
                  onClick={handleSaveAndExit}
                >
                  <Save className="w-4 h-4" />
                  Save & Exit
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Step Indicator — clickable tabs */}
        <div className="sticky top-0 z-10">
          <StepIndicator currentStep={currentStep} onStepClick={setCurrentStep} stepErrorCounts={stepErrorCounts} validationTriggered={validationTriggered} />
        </div>

        {/* Submission overlay */}
        {isSubmitting && (
          <div className="fixed inset-0 bg-[#2A2A2A]/90 flex items-center justify-center z-[100]">
            <SubmissionProgressBar currentStep={submissionStep} totalSteps={6} />
          </div>
        )}

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto">
          {/* Per-step validation error banner */}
          {validationTriggered && (stepErrorCounts[currentStep] || 0) > 0 && (
            <div className="bg-[#FEF2F2] border-b border-[#FCA5A5] px-6 py-2.5 flex items-center gap-2.5">
              <div className="w-6 h-6 rounded-full bg-[#EF4444] flex items-center justify-center shrink-0">
                <AlertCircle className="w-3.5 h-3.5 text-white" />
              </div>
              <span className="text-[13px] text-[#991B1B] font-medium">
                {stepErrorCounts[currentStep]} required field{stepErrorCounts[currentStep] > 1 ? 's' : ''} missing in this step
              </span>
            </div>
          )}
          {/* ═══════ Step 1: Customer / Complaint Details ═══════ */}
          {currentStep === 1 && (
            <Card className="border-0 rounded-none shadow-none overflow-hidden">
              <CardContent className="p-0">
                <div className="grid grid-cols-[1fr_1.2fr_1.2fr] bg-[#2064B7] text-white text-[13px] font-semibold">
                  <div className="px-4 py-2.5">Headers</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Input Fields</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Output</div>
                </div>
                <FormField isInput label="Investigation Officer" output="Staff data matched via Master Key">
                  <Input value={f.investigationOfficer} onChange={e => set('investigationOfficer', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Complaint No" output={`Case received from ${f.caseReceivingChannel} on ${f.caseReceivingDate}, Complaint No. ${f.complaintNo}`}>
                  <Input value={f.complaintNo} onChange={e => set('complaintNo', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Case Receiving Channel" output={f.caseReceivingChannel ? `The case receiving channel fetched from DB MIS is ${f.caseReceivingChannel}.` : '—'}>
                  <Input value={f.caseReceivingChannel} onChange={e => set('caseReceivingChannel', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Dispute Channel" output={f.disputeChannel ? `The disputed transactions were performed through the ${f.disputeChannel} channel.` : '—'}>
                  <Input value={f.disputeChannel} onChange={e => set('disputeChannel', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Fraud Type" output={f.fraudTypeField ? `The reported fraud type is ${f.fraudTypeField}.` : '—'}>
                  <Input value={f.fraudTypeField} onChange={e => set('fraudTypeField', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Case Reference No" output={f.caseReferenceNo ? `Case Reference No ${f.caseReferenceNo} is the unique key used for investigation tracking.` : '—'}>
                  <Input value={f.caseReferenceNo} onChange={e => set('caseReferenceNo', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Dispute Amount At Risk" required error={currentStepErrorKeys.has('disputeAmountAtRisk')} output={`The customer raised dispute against total amount ${f.disputeAmountAtRisk}`}>
                  <Input value={f.disputeAmountAtRisk} onChange={e => set('disputeAmountAtRisk', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Expected Recovery From ON-US Beneficiary" output="No recovery expected from On-us customer accounts">
                  <Input value={f.expectedRecovery} onChange={e => set('expectedRecovery', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Expected Recovery from Member/Bank Beneficiary" output={f.expectedRecoveryMemberBank ? `Expected recovery from member / bank beneficiary is ${f.expectedRecoveryMemberBank}.` : '—'}>
                  <Input value={f.expectedRecoveryMemberBank} onChange={e => set('expectedRecoveryMemberBank', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Disputed Transaction Details" large output={
                  <div className="w-full">
                    <div className="bg-white border border-[#E5E7EB] rounded-lg p-2 text-[10px]">
                      <div className="grid grid-cols-4 gap-1 mb-1 font-semibold text-[#6B7280]">
                        <span>Txn ID</span><span>Beneficiary</span><span>Amount</span><span>Channel</span>
                      </div>
                      {caseData.transactions.map((txn, i) => (
                        <div key={i} className="grid grid-cols-4 gap-1 py-1 border-t border-[#F3F4F6]">
                          <span>{txn.transaction_id}</span>
                          <span>{txn.beneficiary_bank}</span>
                          <span className="text-[#2064B7]">{formatCurrency(txn.disputed_amount)}</span>
                          <span>{txn.channel}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                }>
                  <Input value={f.disputedTxnDetails} onChange={e => set('disputedTxnDetails', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField label="Alert Generated by FMS" required error={currentStepErrorKeys.has('fmsAlertGenerated')} output={f.fmsAlertGenerated === 'yes' ? 'Alert was generated by the Fraud Monitoring System.' : 'Amount under threshold, alerts not generated.'}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.fmsAlertGenerated==='yes'} onChange={v => set('fmsAlertGenerated', v)} label="Yes" />
                    <ChipOption value="no" selected={f.fmsAlertGenerated==='no'} onChange={v => set('fmsAlertGenerated', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Customer Name" output={f.customerNameField ? `Customer name recorded as ${f.customerNameField}.` : '—'}>
                  <Input value={f.customerNameField} onChange={e => set('customerNameField', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Customer Account No" output={f.customerAccountNoField ? `Customer account ${f.customerAccountNoField} has been identified and linked to this case.` : '—'}>
                  <Input value={f.customerAccountNoField} onChange={e => set('customerAccountNoField', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Branch Code" output={f.branchCodeField ? `The customer account is maintained at Branch Code ${f.branchCodeField}.` : '—'}>
                  <Input value={f.branchCodeField} onChange={e => set('branchCodeField', e.target.value)} className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Date(s) Incident Occurred" output={`Disputed transactions debited on ${formatDateText(f.incidentDate)}${f.incidentDateTo ? ` to ${formatDateText(f.incidentDateTo)}` : ''}`}>
                  <div className="grid grid-cols-[1fr_auto_1fr] gap-2 items-center w-full h-full px-2 py-1.5">
                    <DateInputWithIcon type="date" value={f.incidentDate} onChange={e => set('incidentDate', e.target.value)} placeholder="Date 1" />
                    <span className="text-[13px] font-medium text-[#6B7280]">to</span>
                    <DateInputWithIcon type="date" value={f.incidentDateTo} onChange={e => set('incidentDateTo', e.target.value)} placeholder="Date 2" />
                  </div>
                </FormField>
                <FormField isInput label="Case Receiving Date" output={f.caseReceivingDate ? `The case was received on ${formatDateText(f.caseReceivingDate)}.` : '—'}>
                  <DateInputWithIcon type="date" value={f.caseReceivingDate} onChange={e => set('caseReceivingDate', e.target.value)} placeholder="dd/mm/yyyy" />
                </FormField>
              </CardContent>
            </Card>
          )}

          {/* ═══════ Step 2: Investigation (All 29 Fields) ═══════ */}
          {currentStep === 2 && (
            <Card className="border-0 rounded-none shadow-none overflow-hidden">
              <CardContent className="p-0">
                <div className="grid grid-cols-[1fr_1.2fr_1.2fr] bg-[#2064B7] text-white text-[13px] font-semibold">
                  <div className="px-4 py-2.5">Headers</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Input Fields</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Output</div>
                </div>

                {/* Customer Contact Section */}
                <SectionDivider title="Customer Contact" />
                <FormField isInput label="Customer Call at Contact Centre (Date & Time)" required error={currentStepErrorKeys.has('cxCallDatetime')} output={f.cxCallDatetime ? `As per system, customer called helpline on ${formatDateTimeText(f.cxCallDatetime)}.` : '—'}>
                  <DateInputWithIcon type="datetime-local" value={f.cxCallDatetime} onChange={e => set('cxCallDatetime', e.target.value)} placeholder="Auto-picked from CX Excel" />
                </FormField>
                <FormField isInput label="Customer Stance as per Initial Call" required error={currentStepErrorKeys.has('initialCustomerStance')} highlighted={autoFilledFieldKeys.has('initialCustomerStance')} large output={f.initialCustomerStance || 'Customer disowned the transactions, claimed fraud.'}>
                  <AutoGrowTextarea value={f.initialCustomerStance} onChange={e => set('initialCustomerStance', e.target.value)} placeholder="Enter customer's initial stance..." className="h-full" />
                </FormField>
                <FormField label="Call was made to the Customer" required error={currentStepErrorKeys.has('ioCallMade')} highlighted={autoFilledFieldKeys.has('ioCallMade')} output={out('ioCallMade', f.ioCallMade)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.ioCallMade==='yes'} onChange={v => set('ioCallMade', v)} label="Yes" />
                    <ChipOption value="no" selected={f.ioCallMade==='no'} onChange={v => set('ioCallMade', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="Contact Established" required error={currentStepErrorKeys.has('contactEstablished')} output={out('contactEstablished', f.contactEstablished)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.contactEstablished==='yes'} onChange={v => set('contactEstablished', v)} label="Yes" />
                    <ChipOption value="no" selected={f.contactEstablished==='no'} onChange={v => set('contactEstablished', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Customer CLI Number" required error={currentStepErrorKeys.has('customerCli')} output={f.customerCli ? `Customer was contacted on CLI ${f.customerCli}.` : '—'}>
                  <Input value={f.customerCli} onChange={e => set('customerCli', e.target.value)} placeholder="Enter customer CLI number" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Calling RC (Recording Channel)" required error={currentStepErrorKeys.has('rcChannel')} output={f.rcChannel ? `Call recording reference ${f.rcChannel} captured for audit trail.` : '—'}>
                  <Input value={f.rcChannel} onChange={e => set('rcChannel', e.target.value)} placeholder="e.g. 25148" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Customer Communication Date / Time (IO Call)" required error={currentStepErrorKeys.has('ioCallDatetime')} output={f.ioCallDatetime ? `IO call made on ${formatDateTimeText(f.ioCallDatetime)}.` : '—'}>
                  <DateInputWithIcon type="datetime-local" value={f.ioCallDatetime} onChange={e => set('ioCallDatetime', e.target.value)} />
                </FormField>
                <FormField label="Communication Letter Sent" required error={currentStepErrorKeys.has('letterSent')} output={out('letterSent', f.letterSent)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.letterSent==='yes'} onChange={v => set('letterSent', v)} label="Yes" />
                    <ChipOption value="no" selected={f.letterSent==='no'} onChange={v => set('letterSent', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Customer Stance as per IO Call" required error={currentStepErrorKeys.has('ioCallStance')} large output={f.ioCallStance || '—'}>
                  <AutoGrowTextarea value={f.ioCallStance} onChange={e => set('ioCallStance', e.target.value)} placeholder="Enter stance during IO call..." className="h-full" />
                </FormField>
                <FormField label="Customer / Beneficiary SIM Blocked" required error={currentStepErrorKeys.has('simBlocked')} output={out('simBlocked', f.simBlocked)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.simBlocked==='yes'} onChange={v => set('simBlocked', v)} label="Yes" />
                    <ChipOption value="no" selected={f.simBlocked==='no'} onChange={v => set('simBlocked', v)} label="No" />
                  </div>
                </FormField>

                {/* Channel & Device Analysis */}
                <SectionDivider title="Channel & Device Analysis" />
                <FormField isInput label="Customer IB/MB Channel Creation (Date & Time)" required error={currentStepErrorKeys.has('mbCreationDatetime')} output={f.mbCreationDatetime ? `As per system, IB/MB channel was created on ${formatDateTimeText(f.mbCreationDatetime)}.` : '—'}>
                  <DateInputWithIcon type="datetime-local" value={f.mbCreationDatetime} onChange={e => set('mbCreationDatetime', e.target.value)} />
                </FormField>
                <FormField isInput label="Customer Debit Card Creation (Date & Time)" required error={currentStepErrorKeys.has('dcCreationDatetime')} output={f.dcCreationDatetime ? `Debit Card creation observed on ${formatDateTimeText(f.dcCreationDatetime)}.` : '—'}>
                  <DateInputWithIcon type="datetime-local" value={f.dcCreationDatetime} onChange={e => set('dcCreationDatetime', e.target.value)} />
                </FormField>
                <FormField isInput label="Customer Credit Card Creation (Date & Time)" required error={currentStepErrorKeys.has('ccCreationDatetime')} output={f.ccCreationDatetime ? `Credit Card creation observed on ${formatDateTimeText(f.ccCreationDatetime)}.` : 'No Credit Card creation record provided.'}>
                  <DateInputWithIcon type="datetime-local" value={f.ccCreationDatetime} onChange={e => set('ccCreationDatetime', e.target.value)} />
                </FormField>
                <FormField isInput label="Source of IB/MB Channel Creation" required error={currentStepErrorKeys.has('mbCreationSource')} output={f.mbCreationSource ? `IB/MB channel creation source is ${f.mbCreationSource}.` : '—'}>
                  <Input value={f.mbCreationSource} onChange={e => set('mbCreationSource', e.target.value)} placeholder="Enter source of IB/MB channel creation" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField label="HBL Mobile Application Channel Activity Review" required error={currentStepErrorKeys.has('hblMobileAppActivityReview')} highlighted={autoFilledFieldKeys.has('hblMobileAppActivityReview')} output={out('hblMobileAppActivityReview', f.hblMobileAppActivityReview)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.hblMobileAppActivityReview==='yes'} onChange={v => set('hblMobileAppActivityReview', v)} label="Yes" />
                    <ChipOption value="no" selected={f.hblMobileAppActivityReview==='no'} onChange={v => set('hblMobileAppActivityReview', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="User Since (Date / Time)" required error={currentStepErrorKeys.has('userSinceDatetime')} output={f.userSinceDatetime ? `Customer is user since ${formatDateTimeText(f.userSinceDatetime)}.` : '—'}>
                  <DateInputWithIcon type="datetime-local" value={f.userSinceDatetime} onChange={e => set('userSinceDatetime', e.target.value)} />
                </FormField>
                <FormField isInput label="Initial Device (at the time of registration)" required error={currentStepErrorKeys.has('initialDeviceId')} highlighted={autoFilledFieldKeys.has('initialDeviceId')} output={f.initialDeviceId ? `Initial registered device is ${f.initialDeviceId}.` : '—'}>
                  <Input value={f.initialDeviceId} onChange={e => set('initialDeviceId', e.target.value)} placeholder="Enter initial device" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Customer Login ID (User Name)" required error={currentStepErrorKeys.has('loginId')} highlighted={autoFilledFieldKeys.has('loginId')} output={f.loginId ? `Customer login ID ${f.loginId} remained under review.` : '—'}>
                  <Input value={f.loginId} onChange={e => set('loginId', e.target.value)} placeholder="Enter customer login ID" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="User IP Address / LAT / LOG (IP and Lat / Log maybe combined or separate)" required error={currentStepErrorKeys.has('loginIp')} highlighted={autoFilledFieldKeys.has('loginIp')} output={f.loginIp ? `Reviewed user IP/LAT/LONG detail: ${f.loginIp}.` : '—'}>
                  <Input value={f.loginIp} onChange={e => set('loginIp', e.target.value)} placeholder="Enter IP / latitude / longitude" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField label="Date and Time of change of Login ID & Password (last 12 months from the date of disputed transactions)" required error={currentStepErrorKeys.has('credentialChange')} highlighted={autoFilledFieldKeys.has('credentialChange')} output={out('credentialChange', f.credentialChange)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.credentialChange==='yes'} onChange={v => set('credentialChange', v)} label="Yes" />
                    <ChipOption value="no" selected={f.credentialChange==='no'} onChange={v => set('credentialChange', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="Date and Time of change of TPin(last 12 months from the date of disputed transactions)" required error={currentStepErrorKeys.has('tpinChange')} highlighted={autoFilledFieldKeys.has('tpinChange')} output={out('tpinChange', f.tpinChange)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.tpinChange==='yes'} onChange={v => set('tpinChange', v)} label="Yes" />
                    <ChipOption value="no" selected={f.tpinChange==='no'} onChange={v => set('tpinChange', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="Date and Time of change of New Device Registration" required error={currentStepErrorKeys.has('newDevice')} highlighted={autoFilledFieldKeys.has('newDevice')} output={out('newDevice', f.newDevice)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.newDevice==='yes'} onChange={v => set('newDevice', v)} label="Yes" />
                    <ChipOption value="no" selected={f.newDevice==='no'} onChange={v => set('newDevice', v)} label="No" />
                  </div>
                </FormField>

                {/* Limits & Behavioral Analysis */}
                <SectionDivider title="Limits & Behavioral Analysis" />
                <FormField label="Date and Time of Limit Enhancement" required error={currentStepErrorKeys.has('limitEnhanced')} highlighted={autoFilledFieldKeys.has('limitEnhanced')} output={out('limitEnhanced', f.limitEnhanced)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.limitEnhanced==='yes'} onChange={v => set('limitEnhanced', v)} label="Yes" />
                    <ChipOption value="no" selected={f.limitEnhanced==='no'} onChange={v => set('limitEnhanced', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Customer Default / Previous Limit" required error={currentStepErrorKeys.has('previousLimit')} output={f.previousLimit ? `Customer default/previous limit was ${f.previousLimit}.` : '—'}>
                  <Input value={f.previousLimit} onChange={e => set('previousLimit', e.target.value)} placeholder="Enter previous limit" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Customer New Limit, if Change Observed" required error={currentStepErrorKeys.has('newLimit')} output={f.newLimit ? `Customer new limit observed as ${f.newLimit}.` : '—'}>
                  <Input value={f.newLimit} onChange={e => set('newLimit', e.target.value)} placeholder="Enter new limit" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Mode of Limit Enhancement" required error={currentStepErrorKeys.has('limitMode')} output={f.limitMode ? `Limit enhancement mode: ${f.limitMode}.` : 'Not applicable as no enhancement mode recorded.'}>
                  <Input value={f.limitMode} onChange={e => set('limitMode', e.target.value)} placeholder="N/A" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField label="Customer Disputed Transaction Pattern" required error={currentStepErrorKeys.has('txnPattern')} highlighted={autoFilledFieldKeys.has('txnPattern')} output={f.txnPattern || '—'}>
                  <div className="w-full py-2 space-y-2">
                    {txnPatternOptions.map((option) => {
                      const selected = f.txnPattern === option;
                      return (
                        <button
                          key={option}
                          type="button"
                          onClick={() => set('txnPattern', option)}
                          className={cn('w-full inline-flex items-start gap-2 text-left py-1 text-[12px] leading-[1.4] transition-colors', selected ? 'text-[#111827]' : 'text-[#374151]')}
                        >
                          <span
                            className={cn(
                              'mt-0.5 w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 transition-colors',
                              selected ? 'border-[#2064B7]' : 'border-[#D1D5DB]'
                            )}
                          >
                            <span className={cn('w-2.5 h-2.5 rounded-full', selected ? 'bg-[#2064B7]' : 'bg-transparent')} />
                          </span>
                          <span>{option}</span>
                        </button>
                      );
                    })}
                  </div>
                </FormField>
                <FormField label="Change in Device Detail" required error={currentStepErrorKeys.has('deviceChange')} highlighted={autoFilledFieldKeys.has('deviceChange')} output={out('deviceChange', f.deviceChange)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.deviceChange==='yes'} onChange={v => set('deviceChange', v)} label="Yes" />
                    <ChipOption value="no" selected={f.deviceChange==='no'} onChange={v => set('deviceChange', v)} label="No" />
                    <ChipOption value="na" selected={f.deviceChange==='na'} onChange={v => set('deviceChange', v)} label="N/A" />
                  </div>
                </FormField>
                <FormField label="Change of IP / Location" required error={currentStepErrorKeys.has('ipChange')} highlighted={autoFilledFieldKeys.has('ipChange')} output={out('ipChange', f.ipChange)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.ipChange==='yes'} onChange={v => set('ipChange', v)} label="Yes" />
                    <ChipOption value="no" selected={f.ipChange==='no'} onChange={v => set('ipChange', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="Consumer Product Availed (Auto, PIL, CC, ETC)" required error={currentStepErrorKeys.has('productsAvailed')} output={out('productsAvailed', f.productsAvailed)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.productsAvailed==='yes'} onChange={v => set('productsAvailed', v)} label="Yes" />
                    <ChipOption value="no" selected={f.productsAvailed==='no'} onChange={v => set('productsAvailed', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="SMS / OTP Sent to the Customer" required error={currentStepErrorKeys.has('otpDelivered')} highlighted={autoFilledFieldKeys.has('otpDelivered')} output={f.otpDelivered === 'yes' ? 'OTP was delivered to customer.' : f.otpDelivered === 'no' ? 'OTP was not delivered.' : '—'}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.otpDelivered==='yes'} onChange={v => set('otpDelivered', v)} label="Yes" />
                    <ChipOption value="no" selected={f.otpDelivered==='no'} onChange={v => set('otpDelivered', v)} label="No" />
                  </div>
                </FormField>
              </CardContent>
            </Card>
          )}

          {/* ═══════ Step 3: Action Taken (9 Fields) ═══════ */}
          {currentStep === 3 && (
            <Card className="border-0 rounded-none shadow-none overflow-hidden">
              <CardContent className="p-0">
                <div className="grid grid-cols-[1fr_1.2fr_1.2fr] bg-[#2064B7] text-white text-[13px] font-semibold">
                  <div className="px-4 py-2.5">Headers</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Input Fields</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Output</div>
                </div>
                <FormField label="Blocking of Observed Device" required error={currentStepErrorKeys.has('deviceBlockedFlag')} output={out('deviceBlockedFlag', f.deviceBlockedFlag)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.deviceBlockedFlag==='yes'} onChange={v => set('deviceBlockedFlag', v)} label="Yes" />
                    <ChipOption value="no" selected={f.deviceBlockedFlag==='no'} onChange={v => set('deviceBlockedFlag', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="Fraudster / Perpetrator Mobile Number" required error={currentStepErrorKeys.has('fraudsterNumberReported')} output={out('fraudsterNumberReported', f.fraudsterNumberReported)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.fraudsterNumberReported==='yes'} onChange={v => set('fraudsterNumberReported', v)} label="Yes" />
                    <ChipOption value="no" selected={f.fraudsterNumberReported==='no'} onChange={v => set('fraudsterNumberReported', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="FTDH Status / Recovery" large output={f.ftdhStatus ? `As per FTDH status, ${f.ftdhStatus}.` : '—'}>
                  <AutoGrowTextarea value={f.ftdhStatus} onChange={e => set('ftdhStatus', e.target.value)} placeholder="As per FTDH , we observed the status as SF / NSF" className="h-full bg-[#EFF7FF]" />
                </FormField>
                <FormField label="Fund Layered A/C" required error={currentStepErrorKeys.has('fundLayeredFlag')} output={out('fundLayeredFlag', f.fundLayeredFlag)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.fundLayeredFlag==='yes'} onChange={v => set('fundLayeredFlag', v)} label="Yes" />
                    <ChipOption value="no" selected={f.fundLayeredFlag==='no'} onChange={v => set('fundLayeredFlag', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="PSTR" required error={currentStepErrorKeys.has('pstrFlag')} output={out('pstrFlag', f.pstrFlag)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.pstrFlag==='yes'} onChange={v => set('pstrFlag', v)} label="Yes" />
                    <ChipOption value="no" selected={f.pstrFlag==='no'} onChange={v => set('pstrFlag', v)} label="No" />
                  </div>
                </FormField>
                <FormField label="P-II Reviewed" required error={currentStepErrorKeys.has('piiReviewedFlag')} output={out('piiReviewedFlag', f.piiReviewedFlag)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.piiReviewedFlag==='yes'} onChange={v => set('piiReviewedFlag', v)} label="Yes" />
                    <ChipOption value="no" selected={f.piiReviewedFlag==='no'} onChange={v => set('piiReviewedFlag', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Suspected Staff Name (Optional)">
                  <Input value={f.suspectedStaffName} onChange={e => set('suspectedStaffName', e.target.value)} placeholder="NA" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Suspected Staff Feedback" large output={f.suspectedStaffFeedback || 'NA'}>
                  <AutoGrowTextarea value={f.suspectedStaffFeedback} onChange={e => set('suspectedStaffFeedback', e.target.value)} placeholder="NA" className="h-full bg-[#EFF7FF]" />
                </FormField>
                <FormField label="FRMU review on Staff Feedback" required error={currentStepErrorKeys.has('frmuReviewFlag')} output={f.frmuReviewFlag === 'accepted' ? 'Accepted' : f.frmuReviewFlag === 'not_accepted' ? 'Not Accepted' : 'NA'}>
                  <div className="flex gap-3">
                    <ChipOption value="accepted" selected={f.frmuReviewFlag==='accepted'} onChange={v => set('frmuReviewFlag', v)} label="Accepted" />
                    <ChipOption value="not_accepted" selected={f.frmuReviewFlag==='not_accepted'} onChange={v => set('frmuReviewFlag', v)} label="Not Accepted" />
                  </div>
                </FormField>
                <FormField isInput label="Customer Account Opening Date" required error={currentStepErrorKeys.has('customerAccountOpeningDate')} output={f.customerAccountOpeningDate ? `Customer account opening date is ${formatDateText(f.customerAccountOpeningDate)}.` : '—'}>
                  <DateInputWithIcon type="date" value={f.customerAccountOpeningDate} onChange={e => set('customerAccountOpeningDate', e.target.value)} />
                </FormField>
                <FormField isInput label="Customer Account Type" required error={currentStepErrorKeys.has('customerAccountType')} output={f.customerAccountType || '-'}>
                  <Input value={f.customerAccountType} onChange={e => set('customerAccountType', e.target.value)} className="w-full h-full border-0 bg-[#EFF7FF] focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="KYC Review - Debit / Credit Count with amount" required error={currentStepErrorKeys.has('kycReviewDebitCreditCount')} output={f.kycReviewDebitCreditCount || '-'}>
                  <Input value={f.kycReviewDebitCreditCount} onChange={e => set('kycReviewDebitCreditCount', e.target.value)} className="w-full h-full border-0 bg-[#EFF7FF] focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Customer Profile as per system / KYC" required error={currentStepErrorKeys.has('customerProfileKyc')} output={f.customerProfileKyc || '-'}>
                  <Input value={f.customerProfileKyc} onChange={e => set('customerProfileKyc', e.target.value)} className="w-full h-full border-0 bg-[#EFF7FF] focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
              </CardContent>
            </Card>
          )}

          {/* ═══════ Step 4: System Facts / Observations (6 Fields) ═══════ */}
          {currentStep === 4 && (
            <Card className="border-0 rounded-none shadow-none overflow-hidden">
              <CardContent className="p-0">
                <div className="grid grid-cols-[1fr_1.2fr_1.2fr] bg-[#2064B7] text-white text-[13px] font-semibold">
                  <div className="px-4 py-2.5">Headers</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Input Fields</div>
                  <div className="px-4 py-2.5 border-l border-white/20">Output</div>
                </div>
                <FormField label="Any Gap Identified" required error={currentStepErrorKeys.has('gapIdentified')} output={out('gapIdentified', f.gapIdentified)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.gapIdentified==='yes'} onChange={v => set('gapIdentified', v)} label="Yes" />
                    <ChipOption value="no" selected={f.gapIdentified==='no'} onChange={v => set('gapIdentified', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Fact Findings" required error={currentStepErrorKeys.has('factFindings')} large output={f.factFindings ? 'As per retrieved facts, customer performed the transactions.' : '—'}>
                  <AutoGrowTextarea value={f.factFindings} onChange={e => set('factFindings', e.target.value)} placeholder="Enter fact findings..." className="h-full" />
                </FormField>
                <FormField label="Control Breaches" required error={currentStepErrorKeys.has('controlBreaches')} output={out('controlBreaches', f.controlBreaches)}>
                  <div className="flex gap-3">
                    <ChipOption value="yes" selected={f.controlBreaches==='yes'} onChange={v => set('controlBreaches', v)} label="Yes" />
                    <ChipOption value="no" selected={f.controlBreaches==='no'} onChange={v => set('controlBreaches', v)} label="No" />
                  </div>
                </FormField>
                <FormField isInput label="Control Breaches Observed" large output={f.controlBreachesObserved || 'No Control Breach is observed.'}>
                  <AutoGrowTextarea value={f.controlBreachesObserved} onChange={e => set('controlBreachesObserved', e.target.value)} placeholder="Describe observed breaches..." className="h-full" />
                </FormField>
                <FormField isInput label="Root Cause" required error={currentStepErrorKeys.has('rootCause')} output={f.rootCause ? `Root cause identified as: ${f.rootCause}.` : '—'}>
                  <Input value={f.rootCause} onChange={e => set('rootCause', e.target.value)} placeholder="Enter root cause..." className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Type of Fraud Identified by the System" required error={currentStepErrorKeys.has('fraudTypeSystem')} output={f.fraudTypeSystem ? `System fraud classification is ${f.fraudTypeSystem}.` : '—'}>
                  <Input value={f.fraudTypeSystem} onChange={e => set('fraudTypeSystem', e.target.value)} placeholder="Enter fraud type identified by system" className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
              </CardContent>
            </Card>
          )}

          {/* ═══════ Step 5: Conclusion ═══════ */}
          {currentStep === 5 && (
            <Card className="border-0 rounded-none shadow-none overflow-hidden">
              <CardContent className="p-0">
                <div className="grid grid-cols-[1fr_1.2fr_1.2fr] bg-[#2064B7] text-white text-[13px] font-semibold">
                  <div className="px-3 py-2">Headers</div>
                  <div className="px-3 py-2 border-l border-white/20">Input Fields</div>
                  <div className="px-3 py-2 border-l border-white/20">Output</div>
                </div>
                <FormField isInput label="Net Loss Booked" required error={currentStepErrorKeys.has('netLossBooked')} output={f.netLossBooked ? `Net loss of ${f.netLossBooked} was booked.` : 'No loss booked.'}>
                  <Input value={f.netLossBooked} onChange={e => set('netLossBooked', e.target.value)} placeholder="Enter net loss..." className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Conclusion" required error={currentStepErrorKeys.has('finalConclusionType')} large output={f.finalConclusionType ? "No error/gap observed at bank's end. Liability remains at customer's part." : '—'}>
                  <AutoGrowTextarea value={f.finalConclusionType} onChange={e => set('finalConclusionType', e.target.value)} placeholder="Enter conclusion..." className="h-full" />
                </FormField>
                <FormField isInput label="Recommendation" required error={currentStepErrorKeys.has('recommendation')} output={f.recommendation ? `Based on findings, recommendation is: ${f.recommendation}.` : '—'}>
                  <Input value={f.recommendation} onChange={e => set('recommendation', e.target.value)} placeholder="Enter recommendation..." className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Action Owner" required error={currentStepErrorKeys.has('actionOwner')} output={f.actionOwner ? `Matter is referred to ${f.actionOwner}.` : '—'}>
                  <Input value={f.actionOwner} onChange={e => set('actionOwner', e.target.value)} placeholder="Enter action owner..." className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
                <FormField isInput label="Status of Action Recommended" required error={currentStepErrorKeys.has('actionStatus')} output={f.actionStatus ? `Status of recommended action: ${f.actionStatus}.` : '—'}>
                  <Input value={f.actionStatus} onChange={e => set('actionStatus', e.target.value)} placeholder="Enter status..." className="w-full h-full border-0 bg-transparent focus-visible:ring-0 px-4 py-2.5 rounded-none text-[13px]" />
                </FormField>
              </CardContent>
            </Card>
          )}

          {/* ═══════ Step 6: Annx (Evidence) — Modal Design Retained ═══════ */}
          {currentStep === 6 && (
            <Card className="border-0 rounded-none shadow-none overflow-hidden">
              <CardContent className="p-6">
                <input ref={fileInputRef} type="file" multiple accept=".png,.pdf,.jpg,.jpeg,.docx" onChange={e => handleFiles(e.target.files)} className="hidden" />
                <div
                  className={cn(
                    "border-2 border-dashed rounded-xl p-10 bg-[#F9FAFB] flex flex-col items-center justify-center mb-6 transition-all duration-200",
                    isDragOver ? "border-[#2064B7] bg-[#EFF7FF] scale-[1.01]" : "border-[#AFAFAF]"
                  )}
                  onDrop={handleDrop}
                  onDragOver={e => { e.preventDefault(); setIsDragOver(true); }}
                  onDragLeave={e => { e.preventDefault(); setIsDragOver(false); }}
                >
                  <Cloud className="w-14 h-14 text-[#AFAFAF] mb-4" />
                  <p className="text-[16px] text-[#4C4C4C] mb-1 font-medium">Select your file or drag and drop</p>
                  <p className="text-[12px] text-[#AFAFAF] mb-5">png, pdf, jpg, docx accepted</p>
                  <Button className="bg-[#2064B7] hover:bg-[#1a5298] text-white px-8 rounded-lg" onClick={() => fileInputRef.current?.click()}>
                    Attach File
                  </Button>
                </div>
                <div className="space-y-3">
                  {uploadedFiles.map(file => (
                    <div key={file.id} className="flex items-center justify-between bg-[#EFF7FF] border border-[#DAE1E7] rounded-xl p-4 transition-all hover:shadow-sm">
                      <div className="flex items-center gap-4">
                        <div className="relative">
                          <FileText className="w-12 h-12 text-[#AFAFAF]" />
                          <span className="absolute bottom-0 left-0 bg-[#E21F0B] text-white text-[10px] px-1 rounded">{getFileExt(file.name)}</span>
                        </div>
                        <div>
                          <p className="text-[15px] font-medium text-black">{file.name}</p>
                          <p className="text-[12px] text-[#AFAFAF]">
                            {file.size} of {file.totalSize} <span className="mx-2">•</span>
                            <span className="text-[#22C55E] inline-flex items-center gap-1"><Check className="w-3.5 h-3.5" /> {file.status}</span>
                          </p>
                        </div>
                      </div>
                      <button onClick={async () => {
                        if (file.serverFile) {
                          try {
                            await ibmbAPI.deleteInvestigationFile(id, file.id);
                          } catch (err) {
                            console.error('Failed to delete file:', err);
                            toast.error('Failed to delete file');
                            return;
                          }
                        }
                        setUploadedFiles(p => p.filter(x => x.id !== file.id));
                      }} className="p-2 hover:bg-white rounded-full border border-[#4C4C4C] transition-colors">
                        <X className="w-4 h-4 text-[#4C4C4C]" />
                      </button>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* ═══════ Navigation ═══════ */}
          <div className="flex justify-between px-6 py-4 border-t border-[#E5E7EB] bg-white">
            <Button
              variant="outline"
              onClick={() => currentStep === 1 ? navigate(`/cases/${id}`) : setCurrentStep(s => s - 1)}
              className="px-6 border-[#D1D5DB] hover:bg-[#F9FAFB]"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              {currentStep === 1 ? 'Back to Case' : 'Previous'}
            </Button>
            {currentStep < 6 ? (
              <Button onClick={() => setCurrentStep(s => s + 1)} className="px-6 bg-[#2064B7] hover:bg-[#1a5298]">
                Continue
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            ) : (
              <Button className="px-6 bg-[#22C55E] hover:bg-[#16A34A]" onClick={handleReviewReport} disabled={isSubmitting}>
                Review Report
              </Button>
            )}
          </div>
        </div>
      </div>

      <SubmissionSuccessDialog open={showSuccess} onClose={handleSuccessClose} />

      {/* Right-edge vertical tab trigger for Transcription Panel */}
      {currentStep === 2 && !transcriptionOpen && (
        <button
          onClick={() => setTranscriptionOpen(true)}
          className="fixed right-0 top-1/2 -translate-y-1/2 z-40 flex items-center gap-1.5 bg-[#2064B7] text-white px-2 py-3 rounded-l-lg shadow-lg hover:bg-[#1a53a0] transition-all hover:pr-3 group"
          style={{ writingMode: 'vertical-rl', textOrientation: 'mixed' }}
        >
          <Headphones className="w-4 h-4 rotate-90" />
          <span className="text-[11px] font-semibold tracking-wide">Transcriptions</span>
        </button>
      )}

      {/* Transcription Panel Sheet */}
      <TranscriptionPanel
        open={currentStep === 2 && transcriptionOpen}
        onOpenChange={setTranscriptionOpen}
        audioFiles={transcriptionFiles}
        setAudioFiles={setTranscriptionFiles}
        ownerContext={
          investigationId
            ? { owner_type: 'ibmb_investigation', owner_id: investigationId }
            : null
        }
      />
    </>
  );
}

export default InvestigationFormPage;
